//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contractor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividend
    {
        public System.TimeSpan Id { get; set; }
        public System.DateTime Date { get; set; }
        public double NetAmount { get; set; }
        public double TaxCredit { get; set; }
        public double GrossAmount { get; set; }
    }
}
