//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contractor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public string Id { get; set; }
        public ExpenseCategory Category { get; set; }
        public string Description { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime PaidOn { get; set; }
        public PaymentMethod PaidBy { get; set; }
        public ReimbursementMethod ReimbursedBy { get; set; }
    }
}
