//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contractor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public double GrossAmount { get; set; }
        public double NetAmount { get; set; }
        public double Vat { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
