//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contractor.Model
{
    using System;
    
    public enum PaymentMethod : short
    {
        DirectDebit = 0,
        BusinessDebit = 1,
        Cash = 2,
        CommercialCard = 3
    }
}
