//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contractor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime PaidOn { get; set; }
        public double GrossAmount { get; set; }
        public double IncomeTax { get; set; }
        public double EmployersNI { get; set; }
        public double EmployeeNI { get; set; }
        public double NetAmount { get; set; }
    }
}
